@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jan 29 18:15:24 -0800 2025
REM SW Build 5239630 on Fri Nov 08 22:35:27 MST 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim float_add_pipeline_test_behav -key {Behavioral:sim_1:Functional:float_add_pipeline_test} -tclbatch float_add_pipeline_test.tcl -view C:/Users/jayan/Documents/University Of Washington/Education/Masters/2024-2025/Winter/GPU Design Verilog/Project Milestone 1 - Doc and Base Code/src/float/project_1/float_mul_pipeline_test_behav.wcfg -log simulate.log"
call xsim  float_add_pipeline_test_behav -key {Behavioral:sim_1:Functional:float_add_pipeline_test} -tclbatch float_add_pipeline_test.tcl -view C:/Users/jayan/Documents/University Of Washington/Education/Masters/2024-2025/Winter/GPU Design Verilog/Project Milestone 1 - Doc and Base Code/src/float/project_1/float_mul_pipeline_test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
